language: java
jdk:
    - oraclejdk8
install: mvn install -DskipTests=true -q
script: mvn test

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - libstdc++6
